language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install git+https://github.com/xji3/jsonctmctree.git
  - pip install -r requirements.txt
  - pip install .
script:
  - ./test.sh


